### PR TITLE
Added: .gitignore (awaiting review)

### PR DESCRIPTION
**Pull request by Larhra**
Description

Add's .gitignore.

Done:

At the root, Ignored globally the code editor files, dist, node-modules, .env, compiled outputs 

sol addy: D1vH8k5Z92yazAXFhbUcV8SPuUE5M5ifBqExBApVzQYN

### CODE REVIEW

**Comment by roninjin10** [comment]
Check out tevm monorepo for examples of how to make this

**Comment by roninjin10** [comment]
Any luck on this @Larhra ? This pr is blocking others so we will need to finish this up today or else someone else will need to pick it up

**Comment by Larhra** [comment]
Yes, I have made progress, would appreciate if this is reviewed.

**Comment by roninjin10** [comment]
Thanks for the contribution and providing address! I will send a holiday gift of appreciation

**Pull request merged**
